# Generated by Django 5.2.11 on 2026-07-29 10:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('numero_recu', models.CharField(editable=False, max_length=30, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Especes'), ('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Cheque'), ('AUTRE', 'Autre')], max_length=30)),
                ('reference_transaction', models.CharField(blank=True, max_length=150)),
                ('payeur_nom', models.CharField(blank=True, max_length=255)),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('ANNULE', 'Annule'), ('REMBOURSE', 'Rembourse')], default='VALIDE', max_length=20)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_annules', to=settings.AUTH_USER_MODEL)),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='inscriptions.inscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_remboursement', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.TextField()),
                ('mode_remboursement', models.CharField(choices=[('ESPECES', 'Especes'), ('ORANGE_MONEY', 'Orange Money'), ('MOOV_MONEY', 'Moov Money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Cheque'), ('AUTRE', 'Autre')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('effectue_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='paiements.paiement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
