# Generated by Django 5.2.11 on 2026-08-01 11:26

import django.db.models.deletion
from django.db import migrations, models


def normalize_payment_modes(apps, schema_editor):
    Paiement = apps.get_model("paiements", "Paiement")
    Remboursement = apps.get_model("paiements", "Remboursement")
    mapping = {
        "ORANGE_MONEY": "MOBILE_MONEY",
        "MOOV_MONEY": "MOBILE_MONEY",
        "VIREMENT": "BANQUE",
        "CHEQUE": "BANQUE",
    }
    for old_value, new_value in mapping.items():
        Paiement.objects.filter(mode_paiement=old_value).update(
            mode_paiement=new_value
        )
        Remboursement.objects.filter(mode_remboursement=old_value).update(
            mode_remboursement=new_value
        )


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_compte_organisation'),
        ('paiements', '0002_paiement_organisation_remboursement_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements_formations', to='comptes.compte'),
        ),
        migrations.RunPython(normalize_payment_modes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paiement',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Especes'), ('MOBILE_MONEY', 'Paiement mobile'), ('BANQUE', 'Paiement bancaire'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='mode_remboursement',
            field=models.CharField(choices=[('ESPECES', 'Especes'), ('MOBILE_MONEY', 'Paiement mobile'), ('BANQUE', 'Paiement bancaire'), ('CARTE', 'Carte bancaire'), ('AUTRE', 'Autre')], max_length=30),
        ),
    ]
