# Generated by Django 5.2.11 on 2026-07-29 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_inscription', models.DateField(default=django.utils.timezone.localdate)),
                ('prix_initial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('PREINSCRIT', 'Preinscrit'), ('CONFIRME', 'Confirme'), ('EN_COURS', 'En cours'), ('TERMINE', 'Termine'), ('ABANDONNE', 'Abandonne'), ('ANNULE', 'Annule')], default='PREINSCRIT', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('NON_PAYE', 'Non paye'), ('PARTIEL', 'Partiellement paye'), ('PAYE', 'Paye'), ('TROP_PERCU', 'Trop-percu'), ('REMBOURSE', 'Rembourse')], default='NON_PAYE', max_length=20)),
                ('entreprise_payeur', models.CharField(blank=True, max_length=255)),
                ('reference_externe', models.CharField(blank=True, max_length=100)),
                ('observations', models.TextField(blank=True)),
                ('date_annulation', models.DateTimeField(blank=True, null=True)),
                ('motif_annulation', models.TextField(blank=True)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_annulees', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions_creees', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='participants.participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='formations.sessionformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ancien_statut', models.CharField(max_length=20)),
                ('nouveau_statut', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('modifie_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='inscriptions.inscription')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
