# Generated by Django 5.2.11 on 2026-07-29 13:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('cloture', models.BooleanField(default=False, verbose_name='Clôturé')),
                ('date_cloture', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercice comptable',
                'verbose_name_plural': 'Exercices comptables',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='JournalComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('type_journal', models.CharField(choices=[('ACHATS', 'Achats'), ('VENTES', 'Ventes'), ('BANQUE', 'Banque'), ('CAISSE', 'Caisse'), ('OD', 'Opérations Diverses'), ('PAIE', 'Paie'), ('STOCK', 'Stock'), ('IMMO', 'Immobilisations')], max_length=20, verbose_name='Type')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Journal comptable',
                'verbose_name_plural': 'Journaux comptables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_comptable_code', models.CharField(help_text='Code SYSCOHADA du compte banque (521...)', max_length=20, verbose_name='Code compte bancaire')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Solde d'ouverture")),
                ('solde_cloture', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde de clôture')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('RAPPROCHE', 'Rapproché')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('nature', models.CharField(choices=[('ACTIF', 'Actif'), ('PASSIF', 'Passif'), ('CHARGE', 'Charge'), ('PRODUIT', 'Produit'), ('MIXTE', 'Mixte'), ('NEUTRE', 'Neutre')], max_length=10, verbose_name='Nature')),
                ('sens', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit'), ('MIXTE', 'Mixte')], max_length=10, verbose_name='Sens')),
                ('niveau', models.IntegerField(default=1, verbose_name='Niveau')),
                ('type_compte', models.CharField(choices=[('classe', 'Classe'), ('groupe', 'Groupe'), ('compte', 'Compte'), ('sous_compte', 'Sous-compte')], default='compte', max_length=20, verbose_name='Type')),
                ('est_mouvement', models.BooleanField(default=True, verbose_name='Movable')),
                ('categorie', models.CharField(choices=[('bilan', 'Bilan'), ('resultat', 'Résultat'), ('hors_bilan', 'Hors bilan')], default='bilan', max_length=20, verbose_name='Catégorie')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='comptabilite_ohada.comptecomptable', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Compte comptable',
                'verbose_name_plural': 'Comptes comptables',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Mon Entreprise', max_length=200, verbose_name='Nom')),
                ('devise', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('nif', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIF')),
                ('stat', models.CharField(blank=True, max_length=50, null=True, verbose_name='STAT')),
                ('rccm', models.CharField(blank=True, max_length=50, null=True, verbose_name='RCCM')),
                ('est_initialise', models.BooleanField(default=False, verbose_name='Initialisé')),
                ('date_initialisation', models.DateField(blank=True, null=True, verbose_name="Date d'initialisation")),
                ('contrepartie_situation', models.CharField(default='101', max_length=20, verbose_name='Compte de contrepartie')),
                ('compte_caisse_defaut', models.CharField(default='571', max_length=20, verbose_name='Compte caisse défaut')),
                ('compte_banque_defaut', models.CharField(default='521', max_length=20, verbose_name='Compte banque défaut')),
                ('compte_client_defaut', models.CharField(default='411', max_length=20, verbose_name='Compte client défaut')),
                ('compte_fournisseur_defaut', models.CharField(default='401', max_length=20, verbose_name='Compte fournisseur défaut')),
                ('tva_active', models.BooleanField(default=True, verbose_name='TVA active')),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Taux TVA %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comptabilite_ohada.exercicecomptable', verbose_name='Exercice en cours')),
            ],
            options={
                'verbose_name': 'Configuration comptable',
                'verbose_name_plural': 'Configuration comptable',
            },
        ),
        migrations.CreateModel(
            name='Immobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_immobilisation', models.CharField(choices=[('CORPORELLE', 'Immobilisation corporelle'), ('INCORPORELLE', 'Immobilisation incorporelle'), ('FINANCIERE', 'Immobilisation financière')], max_length=20, verbose_name='Type')),
                ('date_acquisition', models.DateField(verbose_name="Date d'acquisition")),
                ('valeur_originale', models.DecimalField(decimal_places=2, max_digits=15, verbose_name="Valeur d'origine")),
                ('valeur_residuelle', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valeur résiduelle')),
                ('duree_ans', models.IntegerField(verbose_name='Durée (années)')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CESSION', 'Cédé'), ('SORTIE', 'Sorti')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_amortissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amortissements', to='comptabilite_ohada.comptecomptable', verbose_name='Compte amortissement')),
                ('compte_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges_amortissement', to='comptabilite_ohada.comptecomptable', verbose_name='Compte charge')),
                ('compte_immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='immobilisations', to='comptabilite_ohada.comptecomptable', verbose_name='Compte immobilisation')),
            ],
            options={
                'verbose_name': 'Immobilisation',
                'verbose_name_plural': 'Immobilisations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('date_ecriture', models.DateField(verbose_name="Date d'écriture")),
                ('libelle', models.TextField(verbose_name='Libellé')),
                ('piece', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pièce')),
                ('validee', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Créé par')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite_ohada.exercicecomptable', verbose_name='Exercice')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite_ohada.journalcomptable', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'ordering': ['-date_ecriture', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Crédit')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Libellé ligne')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite_ohada.comptecomptable', verbose_name='Compte')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite_ohada.ecriturecomptable', verbose_name='Écriture')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écritures",
            },
        ),
        migrations.CreateModel(
            name='PlanAmortissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.DateField(verbose_name='Période')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('amortissement_cumule', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amorti cumulé')),
                ('valeur_nette', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valeur nette')),
                ('ecriture_generee', models.BooleanField(default=False, verbose_name='Écriture générée')),
                ('ecriture_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Réf. écriture')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_amortissement', to='comptabilite_ohada.immobilisation')),
            ],
            options={
                'verbose_name': "Plan d'amortissement",
                'verbose_name_plural': "Plans d'amortissement",
                'ordering': ['periode'],
            },
        ),
        migrations.CreateModel(
            name='LigneReleveBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField(verbose_name='Date')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('sens', models.CharField(choices=[('CREDIT', 'Crédit (entrée)'), ('DEBIT', 'Débit (sortie)')], max_length=10, verbose_name='Sens')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('pointe', models.BooleanField(default=False, verbose_name='Pointé')),
                ('releve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptabilite_ohada.relevebancaire')),
            ],
            options={
                'verbose_name': 'Ligne de relevé',
                'verbose_name_plural': 'Lignes de relevé',
                'ordering': ['date_operation'],
            },
        ),
        migrations.CreateModel(
            name='SoldeInitialComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caisse', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('banque', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('stocks', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('clients', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fournisseurs', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('capital_social', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_initiaux', to='comptabilite_ohada.configurationcomptable')),
            ],
            options={
                'verbose_name': 'Solde initial',
                'verbose_name_plural': 'Soldes initiaux',
            },
        ),
        migrations.AddIndex(
            model_name='comptecomptable',
            index=models.Index(fields=['code'], name='comptabilit_code_7337e4_idx'),
        ),
        migrations.AddIndex(
            model_name='comptecomptable',
            index=models.Index(fields=['parent'], name='comptabilit_parent__a444f9_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['reference'], name='comptabilit_referen_f8620d_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['date_ecriture'], name='comptabilit_date_ec_f8d0e2_idx'),
        ),
        migrations.AddIndex(
            model_name='ecriturecomptable',
            index=models.Index(fields=['journal', 'date_ecriture'], name='comptabilit_journal_30c9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='ligneecriturecomptable',
            index=models.Index(fields=['compte'], name='comptabilit_compte__17d8df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='planamortissement',
            unique_together={('immobilisation', 'periode')},
        ),
    ]
