# Generated by Django 5.2.11 on 2026-07-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite_ohada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneecriturecomptable',
            name='compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite_ohada.comptecomptable', verbose_name='Compte'),
        ),
        migrations.AddConstraint(
            model_name='ligneecriturecomptable',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='ligne_montants_positifs'),
        ),
        migrations.AddConstraint(
            model_name='ligneecriturecomptable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='ligne_un_seul_sens'),
        ),
    ]
