# Generated by Django 5.2.11 on 2026-07-31 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite_ohada', '0003_configurationcomptable_organisation_and_more'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('ENCAISSEMENT', 'Encaissement'), ('DECAISSEMENT', 'Décaissement'), ('TRANSFERT', 'Transfert entre comptes'), ('ANNULATION_ENCAISSEMENT', "Annulation d'encaissement"), ('ANNULATION_DECAISSEMENT', 'Annulation de décaissement'), ('DEPOT_BANQUE', 'Dépôt en banque'), ('RETRAIT_BANQUE', 'Retrait de banque'), ('FACTURE_CLIENT', 'Facture client'), ('PAIEMENT_CLIENT', 'Paiement client'), ('FACTURE_FOURNISSEUR', 'Facture fournisseur'), ('PAIEMENT_FOURNISSEUR', 'Paiement fournisseur'), ('SALAIRE', 'Salaire')], db_index=True, max_length=40, verbose_name="Type d'opération")),
                ('libelle', models.CharField(blank=True, max_length=150, verbose_name='Libellé')),
                ('compte_debit', models.CharField(blank=True, help_text="Laisser vide si le compte est fourni par l'opération.", max_length=20, verbose_name='Compte débité')),
                ('compte_credit', models.CharField(blank=True, help_text="Laisser vide si le compte est fourni par l'opération.", max_length=20, verbose_name='Compte crédité')),
                ('journal_code', models.CharField(default='OD', max_length=10, verbose_name='Journal')),
                ('actif', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Règle comptable',
                'verbose_name_plural': 'Règles comptables',
                'ordering': ['type_operation'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'type_operation'), name='unique_regle_par_organisation')],
            },
        ),
    ]
