# Generated by Django 5.2.11 on 2026-07-29 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
        ('inscriptions', '0001_initial'),
        ('presences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presence',
            options={'ordering': ['seance__date', 'inscription__participant__nom']},
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['seance', 'statut'], name='presences_p_seance__ecbb39_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['inscription', 'statut'], name='presences_p_inscrip_c74537_idx'),
        ),
    ]
