# Generated by Django 5.2.11 on 2026-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(default='', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('numero_fiscal', models.CharField(blank=True, max_length=100)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('prefixe_recu', models.CharField(default='REC', max_length=10)),
                ('prefixe_attestation', models.CharField(default='ATT', max_length=10)),
                ('signature_nom', models.CharField(blank=True, max_length=255)),
                ('signature_fonction', models.CharField(blank=True, max_length=255)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='settings/signatures/')),
                ('cachet_image', models.ImageField(blank=True, null=True, upload_to='settings/cachets/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
