# Generated by Django 5.2.11 on 2026-07-30 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationorganisation',
            name='couleur_accent',
            field=models.CharField(default='#f28b16', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='configurationorganisation',
            name='couleur_fond',
            field=models.CharField(default='#f4f6f9', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='configurationorganisation',
            name='couleur_header',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='configurationorganisation',
            name='couleur_primaire',
            field=models.CharField(default='#15519a', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='configurationorganisation',
            name='couleur_secondaire',
            field=models.CharField(default='#102f5d', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='configurationorganisation',
            name='couleur_sidebar',
            field=models.CharField(default='#0b2448', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='configurationorganisation',
            name='couleur_surface',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='configurationorganisation',
            name='palette',
            field=models.CharField(choices=[('FORMIX', 'Formix'), ('OCEAN', 'Ocean corporate'), ('EMERALD', 'Emerald finance'), ('BORDEAUX', 'Bordeaux premium'), ('CUSTOM', 'Personnalise')], default='FORMIX', max_length=20),
        ),
    ]
