# Generated by Django 5.2.11 on 2026-07-31 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_configurationorganisation_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationorganisation',
            name='couleur_accent',
            field=models.CharField(default='#ef8a1c', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configurationorganisation',
            name='couleur_fond',
            field=models.CharField(default='#f6f5f3', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configurationorganisation',
            name='couleur_primaire',
            field=models.CharField(default='#c2600a', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configurationorganisation',
            name='couleur_secondaire',
            field=models.CharField(default='#9c4a06', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configurationorganisation',
            name='couleur_sidebar',
            field=models.CharField(default='#1f1509', max_length=7, validators=[django.core.validators.RegexValidator(message='Saisissez une couleur au format #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='configurationorganisation',
            name='nom',
            field=models.CharField(default='', max_length=255),
        ),
    ]
