# Generated by Django 5.2.11 on 2026-07-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salaire_mensuel',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Salaire mensuel utilisé par le module de paie simple.', max_digits=12, null=True),
        ),
    ]
