# Generated by Django 5.2.11 on 2026-07-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_salaire_mensuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('RESPONSABLE', 'Responsable formation'), ('FORMATEUR', 'Formateur'), ('COMPTABLE', 'Comptable'), ('RH', 'Responsable RH'), ('CAISSIER', 'Caissier')], default='RESPONSABLE', max_length=20),
        ),
    ]
