# Generated by Django 5.2.11 on 2026-07-28 12:18

from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_rubriques(apps, schema_editor):
    RubriquePaie = apps.get_model("django_paie", "RubriquePaie")
    rubriques = [
        ("BASE", "Salaire de base", "gain", True, False, True, 1),
        ("PRIME", "Primes", "gain", True, False, True, 2),
        ("HSUP", "Heures supplémentaires", "gain", True, False, True, 3),
        ("AVANTAGE", "Avantages en nature", "gain", True, False, True, 4),
        ("ABSENCE", "Absences", "retenue", True, False, True, 5),
        ("CNSS", "Cotisation CNSS", "retenue", False, True, True, 6),
        ("AMO", "Cotisation AMO", "retenue", False, True, True, 7),
        ("ITS", "Impôt sur le traitement et le salaire", "retenue", False, False, True, 8),
    ]
    for code, libelle, type_r, imposable, cotisable, actif, ordre in rubriques:
        RubriquePaie.objects.get_or_create(
            code=code,
            defaults={
                "libelle": libelle,
                "type_rubrique": type_r,
                "imposable": imposable,
                "cotisable": cotisable,
                "actif": actif,
                "ordre": ordre,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('django_paie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gains', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('total_retenues', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('net_a_payer', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('date_edition', models.DateField()),
                ('est_verrouille', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CALCULE', 'Calculé'), ('VERIFIE', 'Vérifié'), ('VALIDE', 'Validé'), ('CLOTURE', 'Clôturé')], default='BROUILLON', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
            },
        ),
        migrations.CreateModel(
            name='CotisationBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cotisation', models.CharField(choices=[('SALARIALE', 'Salariale'), ('PATRONALE', 'Patronale')], max_length=10)),
                ('base', models.DecimalField(decimal_places=0, max_digits=14)),
                ('taux', models.DecimalField(decimal_places=4, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Cotisation du bulletin',
                'verbose_name_plural': 'Cotisations du bulletin',
            },
        ),
        migrations.CreateModel(
            name='LigneBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=0, max_digits=14)),
                ('taux', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=14)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Ligne de bulletin',
                'verbose_name_plural': 'Lignes de bulletin',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RubriquePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_rubrique', models.CharField(choices=[('gain', 'Gain'), ('retenue', 'Retenue')], max_length=10)),
                ('imposable', models.BooleanField(default=True)),
                ('cotisable', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rubrique de paie',
                'verbose_name_plural': 'Rubriques de paie',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ValidationPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('CALCULE', 'Calculé'), ('VERIFIE', 'Vérifié'), ('VALIDE', 'Validé'), ('CLOTURE', 'Clôturé')], max_length=10)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Validation de paie',
                'verbose_name_plural': 'Validations de paie',
                'ordering': ['-date_action'],
            },
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='echeance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_detail', to='django_paie.echeancesalariale'),
        ),
        migrations.AddField(
            model_name='cotisationbulletin',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='django_paie.bulletinpaie'),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='django_paie.bulletinpaie'),
        ),
        migrations.AddField(
            model_name='lignebulletin',
            name='rubrique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_paie.rubriquepaie'),
        ),
        migrations.AddField(
            model_name='cotisationbulletin',
            name='rubrique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='django_paie.rubriquepaie'),
        ),
        migrations.AddField(
            model_name='validationpaie',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='django_paie.bulletinpaie'),
        ),
        migrations.AddField(
            model_name='validationpaie',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(seed_default_rubriques, migrations.RunPython.noop),
    ]
