# Generated by Django 5.2.11 on 2026-07-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_paie', '0003_alter_paiementsalarial_type_paiement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='echeancesalariale',
            new_name='django_paie_employe_f40cfa_idx',
            old_name='django_paie_employe_content_type_employe_object_id_idx',
        ),
        migrations.RenameIndex(
            model_name='echeancesalariale',
            new_name='django_paie_entrepr_fd7f96_idx',
            old_name='django_paie_entreprise_id_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='echeancesalariale',
            new_name='django_paie_annee_36b2f5_idx',
            old_name='django_paie_annee_mois_entreprise_id_idx',
        ),
    ]
