# Generated by Django 5.2.11 on 2026-07-28 15:47

import django.db.models.deletion
from datetime import date
from django.db import migrations, models


def seed_regles_et_rubriques(apps, schema_editor):
    ReglePaie = apps.get_model("django_paie", "ReglePaie")
    RubriquePaie = apps.get_model("django_paie", "RubriquePaie")
    ReglePaie.objects.get_or_create(
        pays="ML", organisme="CNSS", version=1, entreprise_id="",
        defaults={
            "date_debut": date(2000, 1, 1),
            "taux_salarial": "0.036",
            "taux_patronal": "0.072",
            "plafond": 350000,
        },
    )
    ReglePaie.objects.get_or_create(
        pays="ML", organisme="AMO", version=1, entreprise_id="",
        defaults={
            "date_debut": date(2000, 1, 1),
            "taux_salarial": "0.05",
            "taux_patronal": "0.06",
        },
    )
    ReglePaie.objects.get_or_create(
        pays="ML", organisme="ITS", version=1, entreprise_id="",
        defaults={
            "date_debut": date(2000, 1, 1),
            "parametres": {
                "abattement_forfaitaire": "0.10",
                "decote_seuil": 100000,
                "decote_montant": 10000,
                "baremes": [
                    {"seuil": 51000, "taux": "0"},
                    {"seuil": 86000, "taux": "0.03"},
                    {"seuil": 149000, "taux": "0.10"},
                    {"seuil": 262000, "taux": "0.15"},
                    {"seuil": 400000, "taux": "0.20"},
                    {"seuil": 700000, "taux": "0.25"},
                    {"seuil": None, "taux": "0.30"},
                ],
            },
        },
    )
    rubriques = [
        ("INDEMNITE", "Indemnités", "gain", True, True, 3),
        ("RAPPEL", "Rappels", "gain", True, True, 5),
        ("CONGE", "Congés payés", "gain", True, True, 6),
        ("REGULARISATION", "Régularisations", "gain", True, True, 7),
        ("PRET_AVANCE", "Prêts et avances récupérables", "retenue", False, False, 11),
        ("RETENUE", "Retenues personnalisées", "retenue", False, False, 12),
    ]
    for code, libelle, type_rubrique, imposable, cotisable, ordre in rubriques:
        RubriquePaie.objects.get_or_create(
            code=code,
            defaults={
                "libelle": libelle,
                "type_rubrique": type_rubrique,
                "imposable": imposable,
                "cotisable": cotisable,
                "actif": True,
                "ordre": ordre,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_paie', '0004_rename_django_paie_employe_content_type_employe_object_id_idx_django_paie_employe_f40cfa_idx_and_mor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(default='ML', max_length=2)),
                ('organisme', models.CharField(choices=[('CNSS', 'CNSS'), ('AMO', 'AMO'), ('ITS', 'ITS')], max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('entreprise_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('taux_salarial', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('taux_patronal', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('plafond', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('parametres', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Règle de paie',
                'verbose_name_plural': 'Règles de paie',
                'ordering': ['organisme', '-date_debut', '-version'],
                'constraints': [models.UniqueConstraint(fields=('pays', 'organisme', 'version', 'entreprise_id'), name='paie_regle_version_unique')],
            },
        ),
        migrations.CreateModel(
            name='VariablePaieMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_object_id', models.CharField(max_length=255)),
                ('mois', models.PositiveSmallIntegerField()),
                ('annee', models.PositiveSmallIntegerField()),
                ('entreprise_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('primes', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('indemnites', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('taux_majoration_heures', models.DecimalField(decimal_places=4, default=1.25, max_digits=6)),
                ('avantages_nature', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('prets_avances', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('retenues_personnalisees', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('rappels', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('conges_payes', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('regularisations', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('jours_absence', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('autres', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Variable mensuelle de paie',
                'verbose_name_plural': 'Variables mensuelles de paie',
                'constraints': [models.UniqueConstraint(fields=('employe_content_type', 'employe_object_id', 'mois', 'annee', 'entreprise_id'), name='paie_variable_unique')],
            },
        ),
        migrations.RunPython(seed_regles_et_rubriques, migrations.RunPython.noop),
    ]
