# Generated by Django 5.2.11 on 2026-07-28 18:23

import django.db.models.deletion
from django.db import migrations, models


def corriger_rubriques_cotisables(apps, schema_editor):
    RubriquePaie = apps.get_model("django_paie", "RubriquePaie")
    valeurs = {
        "BASE": {"imposable": True, "cotisable": True},
        "PRIME": {"imposable": True, "cotisable": True},
        "HSUP": {"imposable": True, "cotisable": True},
        "AVANTAGE": {"imposable": True, "cotisable": True},
        "ABSENCE": {"imposable": True, "cotisable": True},
    }
    for code, champs in valeurs.items():
        RubriquePaie.objects.filter(code=code).update(**champs)


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_paie', '0005_reglepaie_variablepaiemensuelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpaie',
            name='echeance',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_detail', to='django_paie.echeancesalariale'),
        ),
        migrations.AlterField(
            model_name='paiementsalarial',
            name='echeance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='django_paie.echeancesalariale'),
        ),
        migrations.RunPython(corriger_rubriques_cotisables, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='echeancesalariale',
            constraint=models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='paie_echeance_mois_valide'),
        ),
        migrations.AddConstraint(
            model_name='echeancesalariale',
            constraint=models.CheckConstraint(condition=models.Q(('annee__gte', 2000), ('annee__lte', 2100)), name='paie_echeance_annee_valide'),
        ),
        migrations.AddConstraint(
            model_name='echeancesalariale',
            constraint=models.CheckConstraint(condition=models.Q(('date_debut__lte', models.F('date_fin'))), name='paie_echeance_dates_valides'),
        ),
        migrations.AddConstraint(
            model_name='echeancesalariale',
            constraint=models.CheckConstraint(condition=models.Q(('montant_brut__gte', 0)), name='paie_echeance_brut_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='echeancesalariale',
            constraint=models.CheckConstraint(condition=models.Q(('montant_net__gte', 0)), name='paie_echeance_net_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='echeancesalariale',
            constraint=models.CheckConstraint(condition=models.Q(('montant_paye__gte', 0)), name='paie_echeance_paye_non_negatif'),
        ),
        migrations.AddConstraint(
            model_name='paiementsalarial',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='paie_paiement_montant_positif'),
        ),
        migrations.AddConstraint(
            model_name='paiementsalarial',
            constraint=models.CheckConstraint(condition=models.Q(('mois_concerne__gte', 1), ('mois_concerne__lte', 12)), name='paie_paiement_mois_valide'),
        ),
        migrations.AddConstraint(
            model_name='paiementsalarial',
            constraint=models.CheckConstraint(condition=models.Q(('annee_concerne__gte', 2000), ('annee_concerne__lte', 2100)), name='paie_paiement_annee_valide'),
        ),
    ]
