# Generated by Django 5.2.11 on 2026-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_paie', '0006_alter_bulletinpaie_echeance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglepaie',
            name='date_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglepaie',
            name='notes_legales',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reglepaie',
            name='source_reglementaire',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reglepaie',
            name='statut_verification',
            field=models.CharField(choices=[('NON_VERIFIE', 'Non vérifié'), ('PROVISOIRE', 'Provisoire'), ('VERIFIE', 'Vérifié'), ('EXPIRE', 'Expiré')], default='NON_VERIFIE', max_length=20),
        ),
    ]
