# Generated by Django 5.2.11 on 2026-07-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(editable=False, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('genre', models.CharField(choices=[('HOMME', 'Homme'), ('FEMME', 'Femme'), ('AUTRE', 'Autre'), ('NON_PRECISE', 'Non precise')], default='NON_PRECISE', max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=150)),
                ('pays', models.CharField(default='Mali', max_length=100)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('entreprise', models.CharField(blank=True, max_length=255)),
                ('personne_contact', models.CharField(blank=True, max_length=255)),
                ('telephone_contact', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/photos/')),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ARCHIVE', 'Archive')], default='ACTIF', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('CNI', "Carte nationale d'identite"), ('PASSEPORT', 'Passeport'), ('PHOTO', 'Photo'), ('DIPLOME', 'Diplome'), ('AUTRE', 'Autre')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='participants/documents/')),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='participants.participant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
