# Generated by Django 5.2.11 on 2026-07-29 10:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_delivrance', models.DateField(default=django.utils.timezone.localdate)),
                ('nom_participant', models.CharField(max_length=255)),
                ('nom_formation', models.CharField(max_length=255)),
                ('titre_session', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_texte', models.CharField(max_length=100)),
                ('formateur_nom', models.CharField(max_length=255)),
                ('taux_presence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='documents/attestations/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('GENEREE', 'Generee'), ('ANNULEE', 'Annulee')], default='BROUILLON', max_length=20)),
                ('motif_annulation', models.TextField(blank=True)),
                ('generee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attestation', to='inscriptions.inscription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_document', models.CharField(choices=[('RECU', 'Recu de paiement'), ('ATTESTATION', 'Attestation'), ('LISTE_PARTICIPANTS', 'Liste des participants'), ('FEUILLE_PRESENCE', 'Feuille de presence'), ('RAPPORT_SESSION', 'Rapport de session')], max_length=30)),
                ('reference', models.CharField(max_length=100)),
                ('fichier', models.FileField(upload_to='documents/generated/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('genere_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
