# Generated by Django 5.2.11 on 2026-07-29 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestation',
            options={'ordering': ['-date_delivrance', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='documentgenere',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='documentgenere',
            constraint=models.UniqueConstraint(fields=('type_document', 'reference'), name='unique_document_type_reference'),
        ),
    ]
