# Generated by Django 5.2.11 on 2026-07-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('STARTER', 'Starter'), ('PREMIUM', 'Premium'), ('PRO', 'Pro')], max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_annuel', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_utilisateurs', models.PositiveIntegerField()),
                ('max_participants', models.PositiveIntegerField()),
                ('max_formations_actives', models.PositiveIntegerField()),
                ('max_stockage_mo', models.PositiveIntegerField()),
                ('fonctionnalites', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['ordre', 'prix_mensuel'],
            },
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], default='MENSUEL', max_length=20)),
                ('statut', models.CharField(choices=[('ESSAI', 'Essai'), ('ACTIF', 'Actif'), ('EN_ATTENTE', 'En attente'), ('EXPIRE', 'Expire'), ('SUSPENDU', 'Suspendu'), ('ANNULE', 'Annule')], db_index=True, default='ESSAI', max_length=20)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('renouvellement_automatique', models.BooleanField(default=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jours_grace', models.PositiveIntegerField(default=3)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='organisations.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='subscriptions.planabonnement')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='PaiementAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('ECHOUE', 'Echoue'), ('ANNULE', 'Annule'), ('REMBOURSE', 'Rembourse')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('donnees_prestataire', models.JSONField(blank=True, default=dict)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='subscriptions.abonnement')),
            ],
            options={
                'verbose_name': "Paiement d'abonnement",
                'verbose_name_plural': "Paiements d'abonnement",
                'ordering': ['-created_at'],
            },
        ),
    ]
