# Generated by Django 5.2.11 on 2026-07-24 11:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type', models.CharField(choices=[('ESPECES', 'Espèces'), ('BANQUE', 'Compte bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte de crédit/débit'), ('PORTEFEUILLE_NUMERIQUE', 'Portefeuille numérique'), ('AUTRE', 'Autre')], default='ESPECES', max_length=30, verbose_name='Type')),
                ('role', models.CharField(blank=True, choices=[('PRINCIPAL', 'Principal'), ('POINT_VENTE', 'Point de vente'), ('CAISSE', 'Caisse'), ('EPARGNE', 'Épargne'), ('ENCAISSEMENT', 'Encaissement'), ('DECAISSEMENT', 'Décaissement')], max_length=20, null=True, verbose_name='Rôle')),
                ('devise', models.CharField(default='XOF', max_length=10, verbose_name='Devise')),
                ('taux_change', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12, verbose_name='Taux de change')),
                ('devise_reference', models.CharField(blank=True, default='', max_length=10, verbose_name='Devise de référence')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Solde actuel')),
                ('dernier_recalcul', models.DateTimeField(blank=True, null=True, verbose_name='Dernier recalcul du solde')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('autoriser_decouvert', models.BooleanField(default=False, verbose_name='Autoriser le découvert')),
                ('limite_decouvert', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Limite de découvert')),
                ('date_ouverture', models.DateField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('date_fermeture', models.DateField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('compte_comptable_code', models.CharField(blank=True, default='', help_text='Code du plan comptable (ex: 5711, 5211, 5811). Lien symbolique, pas une FK.', max_length=20, verbose_name='Code compte comptable SYSCOHADA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Compte financier',
                'verbose_name_plural': 'Comptes financiers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_changement', models.CharField(choices=[('NOM', 'Changement de nom'), ('TYPE', 'Changement de type'), ('ROLE', 'Changement de rôle'), ('ACTIVATION', 'Activation du compte'), ('DESACTIVATION', 'Désactivation du compte'), ('DECOUVERT', 'Modification du découvert'), ('LIMITE', 'Modification de la limite'), ('DEVISE', 'Changement de devise'), ('FERMETURE', 'Fermeture du compte'), ('RECALCUL', 'Recalcul du solde'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de changement')),
                ('ancienne_valeur', models.TextField(blank=True, default='', verbose_name='Ancienne valeur')),
                ('nouvelle_valeur', models.TextField(blank=True, default='', verbose_name='Nouvelle valeur')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='comptes.compte', verbose_name='Compte')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Historique du compte',
                'verbose_name_plural': 'Historiques des comptes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_journal', models.DateField(auto_now_add=True, verbose_name='Date du journal')),
                ('solde_ouverture', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name="Solde d'ouverture")),
                ('total_entrees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total entrées')),
                ('total_sorties', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total sorties')),
                ('solde_theorique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Solde théorique')),
                ('solde_reel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Solde réel')),
                ('ecart', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Écart')),
                ('cloture', models.BooleanField(default=False, verbose_name='Clôturé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='comptes.compte', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Journal de compte',
                'verbose_name_plural': 'Journaux de comptes',
                'ordering': ['-date_journal'],
                'unique_together': {('compte', 'date_journal')},
            },
        ),
        migrations.CreateModel(
            name='LigneJournalCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=50, verbose_name="Type d'opération")),
                ('nature', models.CharField(blank=True, default='', max_length=20, verbose_name='Nature')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('sens', models.CharField(max_length=10, verbose_name='Sens')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptes.journalcompte', verbose_name='Journal')),
            ],
            options={
                'verbose_name': 'Ligne de journal',
                'verbose_name_plural': 'Lignes de journal',
            },
        ),
        migrations.CreateModel(
            name='MouvementCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('ENCAISSEMENT', 'Encaissement'), ('DECAISSEMENT', 'Décaissement'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement'), ('OUVERTURE', 'Solde initial / Ouverture'), ('CLOTURE', 'Clôture'), ('ANNULATION', 'Annulation')], default='ENCAISSEMENT', max_length=20, verbose_name='Nature')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('RAPPROCHE', 'Rapproché')], default='VALIDE', max_length=20, verbose_name='Statut')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('annule', models.BooleanField(default=False, verbose_name='Annulé')),
                ('annule_le', models.DateTimeField(blank=True, null=True, verbose_name='Annulé le')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('annule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_annules', to=settings.AUTH_USER_MODEL, verbose_name='Annulé par')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='comptes.compte', verbose_name='Compte')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('mouvement_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annulations', to='comptes.mouvementcompte', verbose_name='Mouvement parent')),
            ],
            options={
                'verbose_name': 'Mouvement',
                'verbose_name_plural': 'Mouvements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RapprochementBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField(verbose_name='Date fin')),
                ('date_releve', models.DateField(verbose_name='Date du relevé')),
                ('solde_releve', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde relevé')),
                ('solde_comptable', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde comptable')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('PARTIEL', 'Partiel'), ('EQUILIBRE', 'Équilibré'), ('ECART', 'Écart constaté')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements', to='comptes.compte', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Rapprochement bancaire',
                'verbose_name_plural': 'Rapprochements bancaires',
                'ordering': ['-date_fin'],
            },
        ),
        migrations.CreateModel(
            name='LigneRapprochement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ligne', models.CharField(choices=[('RELEVE', 'Relevé'), ('COMPTABLE', 'Comptable'), ('ECART', 'Écart')], max_length=10, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('date_operation', models.DateField(verbose_name='Date opération')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('pointe', models.BooleanField(default=False, verbose_name='Pointé')),
                ('commentaire', models.CharField(blank=True, default='', max_length=255, verbose_name='Commentaire')),
                ('mouvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_rapprochement', to='comptes.mouvementcompte', verbose_name='Mouvement')),
                ('rapprochement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='comptes.rapprochementbancaire', verbose_name='Rapprochement')),
            ],
            options={
                'verbose_name': 'Ligne de rapprochement',
                'verbose_name_plural': 'Lignes de rapprochement',
            },
        ),
        migrations.CreateModel(
            name='TransfertCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='comptes.compte', verbose_name='Destination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='comptes.compte', verbose_name='Source')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Transfert',
                'verbose_name_plural': 'Transferts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ClotureCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('QUOTIDIENNE', 'Quotidienne'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUELLE', 'Mensuelle'), ('TRIMESTRIELLE', 'Trimestrielle'), ('ANNUELLE', 'Annuelle')], default='QUOTIDIENNE', max_length=20, verbose_name='Période')),
                ('date_cloture', models.DateField(verbose_name='Date de clôture')),
                ('solde_avant', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde avant clôture')),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde après clôture')),
                ('ecart', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Clôturé par')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clotures', to='comptes.compte', verbose_name='Compte')),
            ],
            options={
                'verbose_name': 'Clôture de compte',
                'verbose_name_plural': 'Clôtures de comptes',
                'ordering': ['-date_cloture'],
                'unique_together': {('compte', 'periode', 'date_cloture')},
            },
        ),
        migrations.CreateModel(
            name='CompteFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_defaut', models.BooleanField(default=False, help_text="Proposé par défaut lors d'un encaissement", verbose_name='Compte par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='comptes.compte', verbose_name='Compte')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_favoris', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compte favori',
                'verbose_name_plural': 'Comptes favoris',
                'ordering': ['ordre', 'compte__nom'],
                'unique_together': {('compte', 'utilisateur')},
            },
        ),
        migrations.AddIndex(
            model_name='mouvementcompte',
            index=models.Index(fields=['compte', 'date'], name='comptes_mou_compte__ea1dca_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcompte',
            index=models.Index(fields=['reference'], name='comptes_mou_referen_a3d100_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementcompte',
            index=models.Index(fields=['statut'], name='comptes_mou_statut_fd7985_idx'),
        ),
    ]
