# Generated by Django 5.2.11 on 2026-07-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_alter_mouvementcompte_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementcompte',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
