# Generated by Django 5.2.11 on 2026-07-29 21:25

from django.db import migrations, models


def backfill_movement_direction(apps, schema_editor):
    MouvementCompte = apps.get_model("comptes", "MouvementCompte")
    MouvementCompte.objects.filter(
        nature__in=["DECAISSEMENT", "CLOTURE", "ANNULATION"]
    ).update(sens="SORTIE")


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_mouvementcompte_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementcompte',
            name='sens',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], default='ENTREE', max_length=10, verbose_name='Sens'),
        ),
        migrations.RunPython(
            backfill_movement_direction,
            migrations.RunPython.noop,
        ),
    ]
