# Generated by Django 5.2.11 on 2026-07-30 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organisations/logos/')),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=150)),
                ('pays', models.CharField(default='Mali', max_length=100)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('fuseau_horaire', models.CharField(default='Africa/Bamako', max_length=100)),
                ('statut', models.CharField(choices=[('ESSAI', "Periode d'essai"), ('ACTIVE', 'Active'), ('SUSPENDUE', 'Suspendue'), ('EXPIREE', 'Abonnement expire'), ('FERMEE', 'Fermee')], db_index=True, default='ESSAI', max_length=20)),
                ('date_fin_essai', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MembreOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('PROPRIETAIRE', 'Proprietaire'), ('ADMIN', 'Administrateur'), ('RESPONSABLE', 'Responsable formation'), ('FORMATEUR', 'Formateur'), ('COMPTABLE', 'Comptable'), ('LECTURE', 'Lecture seule')], max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_organisations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='organisations.organisation')),
            ],
            options={
                'verbose_name': "Membre d'organisation",
                'verbose_name_plural': "Membres d'organisation",
                'ordering': ['organisation__nom', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'user'), name='unique_user_organisation')],
            },
        ),
    ]
