# Generated by Django 5.2.11 on 2026-08-01 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptabilite_ohada', '0004_regle_comptable'),
        ('comptes', '0005_compte_organisation'),
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(db_index=True, max_length=30, verbose_name='Numéro')),
                ('date_operation', models.DateField(db_index=True, verbose_name='Date')),
                ('type_operation', models.CharField(db_index=True, max_length=40, verbose_name="Type d'opération")),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('devise', models.CharField(default='FCFA', max_length=10, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], db_index=True, default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='operations/justificatifs/', verbose_name='Justificatif')),
                ('centre_cout', models.CharField(blank=True, max_length=100, verbose_name='Centre de coût')),
                ('projet', models.CharField(blank=True, max_length=100, verbose_name='Projet')),
                ('module_source', models.CharField(blank=True, help_text="Renseigné quand l'opération est créée par un autre module.", max_length=50, verbose_name="Module d'origine")),
                ('validee_le', models.DateTimeField(blank=True, null=True, verbose_name='Validée le')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('compte_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations_recues', to='comptes.compte', verbose_name='Compte de destination')),
                ('compte_tresorerie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='comptes.compte', verbose_name='Compte de trésorerie')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_creees', to=settings.AUTH_USER_MODEL)),
                ('ecriture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation', to='comptabilite_ohada.ecriturecomptable', verbose_name='Écriture générée')),
                ('mouvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='comptes.mouvementcompte', verbose_name='Mouvement financier')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-date_operation', '-id'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'numero'), name='unique_numero_operation_par_organisation')],
            },
        ),
    ]
