# Generated by Django 5.2.11 on 2026-07-29 10:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#2563EB', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=30, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('objectifs', models.TextField(blank=True)),
                ('programme', models.TextField(blank=True)),
                ('duree', models.PositiveIntegerField()),
                ('unite_duree', models.CharField(choices=[('HEURES', 'Heures'), ('JOURS', 'Jours'), ('SEMAINES', 'Semaines')], default='HEURES', max_length=20)),
                ('prix_standard', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/images/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIVE', 'Active'), ('ARCHIVEE', 'Archivee')], default='BROUILLON', max_length=20)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formations', to='formations.categorieformation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=30, unique=True)),
                ('titre', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(max_length=255)),
                ('capacite_max', models.PositiveIntegerField(default=20)),
                ('prix_applique', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('seuil_presence_attestation', models.DecimalField(decimal_places=2, default=75, max_digits=5)),
                ('paiement_requis_attestation', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PLANIFIEE', 'Planifiee'), ('INSCRIPTIONS_OUVERTES', 'Inscriptions ouvertes'), ('COMPLETE', 'Complete'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='BROUILLON', max_length=30)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_formateur', to=settings.AUTH_USER_MODEL)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='formations.formation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('contenu', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiee'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminee'), ('ANNULEE', 'Annulee')], default='PLANIFIEE', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='formations.sessionformation')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'constraints': [models.UniqueConstraint(fields=('session', 'date', 'heure_debut'), name='unique_seance_session_date_heure')],
            },
        ),
    ]
