# Generated by Django 5.2.11 on 2026-08-01 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_categorieformation_organisation_and_more'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_regenerated_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisation')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_access', to='formations.sessionformation')),
            ],
            options={
                'verbose_name': 'Lien public de session',
                'verbose_name_plural': 'Liens publics de session',
                'ordering': ['-created_at'],
            },
        ),
    ]
